### ISSUE TITLE
 Can't open ./docker/start.sh bug

### ISSUE THREAD

**Issue by JuPlutonic** [apsislabs/rails_starter#1]
```
#! /bin/bash

# Wait for PostgreSQL
....
```
when try docker-compose up I get `rails_starter_ror | sh: 0: Can't open ./docker/start.sh`
The same error `sh: 0: Can't open ./docker/start.sh` I see in the OracleVB where I used **docker logs rails_starter_ror** command

**Comment by HenryKeiter** [comment]
@JuPlutonic What host platform are you on? If you're using Docker for Windows, you'll have to map a shared drive (in VirtualBox) on your docker machine to a directory with access to the rest of the project files. I typically just map my project drive from the root, so I have Shared Machine Folders in VirtualBox set up like this:

```
|   name  |     path     |
|---------|--------------|
| c/Users | \\?\c:\Users |
| d       | D:\          |
```

**Comment by egreer** [comment]
@JuPlutonic I believe this is resolved with the comment by @HenryKeiter or in the general update:
https://github.com/apsislabs/rails_starter/pull/3

Let me know if you are still running into an issue and we can reopen this.
